[package]
name = "ride-the-bus-mcts"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.28.1"
itertools = "0.14.0"
rand = "0.9.0"
ratatui = "0.29.0"
tui-textarea = "0.7.0"

[profile.dev]
panic = 'abort'
